version: "3"

services:
  postgres-db:
    restart: always
    image: postgres:latest
    environment:
      TZ: "Asia/Tehran"
      POSTGRES_DB: bookLand_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U admin -d bookLand_db"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - my_network
    volumes:
       - ./db-data/postgres/:/var/lib/postgresql/data/
#      - ./SqlScripts.sql:/docker-entrypoint-initdb.d/SqlScripts.sql


  user_service:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=postgres-db
      - FILE_SERVER=http://file-server:8080
    networks:
      - my_network
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      postgres-db:
        condition: service_healthy

networks: # Note that network must be created before running compose with this network
  my_network:
    external: true

