version: "3.8"

services:
  user_service:
    build:
      context: .
      dockerfile: ./bookLand_microservice.dockerfile
    networks:
      - db_network
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: gunicorn --bind 0.0.0.0:8000 bookLand_microservice.wsgi:application

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BookLandDB
    ports:
      - "5432:5432"
    networks:
      - db_network
    volumes:
      - ./SqlScripts.sql:/docker-entrypoint-initdb.d/SqlScripts.sql
      - ./db-data/postgres/:/var/lib/postgresql/data/

networks:
  db_network:
